spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #正式库。
    #url: jdbc:mysql://180.76.96.83:3306/ocr?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8

    #测试库
    url: jdbc:mysql://localhost:3306/yuantong?autoReconnect=true&useUnicode=true&characterEncoding=utf8

    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: eFnhwUYi&8Nf
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  tomcat:
    max-http-post-size: 0
  servlet:
    context-path: /